{
    'name': "Website Conecta",
    'version': "0.1",
    'author': "Communities - Comunicações, Lda",
    'category': "Openerp CMS",
    'summary': "Company directory",
    'description': """
        Descrever o módulo
    """,
    'author': 'Communities - Comunicações',
    'website': 'http://www.communities.pt',
    'depends': ['web',
    'crm',
    'website',
    'website_blog',
    'snippet_latest_posts',
    'website_crm',
    'base_geolocalize',
    'project',
    'event',
    'base_multi_image',
    'website_event',
    'project_issue',
    ],
    'data': [
        'views/res_partner_views.xml',
        'views/res_country_state_city.xml',
        'views/res_country_state_city_import.xml',
        'views/res_country_state_views.xml',
        'views/website_conecta_templates.xml',
        'views/website_conecta_events.xml',
        'views/res_conecta_questionnaire_views.xml',
        'views/res_conecta_questionnaire_answer_views.xml',

        'views/homepage_template.xml',
        'views/website_assets.xml',
        'views/pages_template.xml',

        'views/res_partner_interest_views.xml',
        'views/res_partner_interest_category_views.xml',
        'views/menus_views.xml',
        'data/res.partner.categ.csv',
        'data/website.menu.csv',
        'data/res.partner.relation.csv',
        'data/res.groups.csv',
        'data/ir.rule.csv',
        'demo/res.conecta.questionnaire.csv',
        'demo/res.conecta.questionnaire.question.csv',
        'demo/res.conecta.questionnaire.question.option.csv',
        'demo/res.conecta.questionnaire.matchingrules.csv',
        'demo/res.partner.interest.category.csv',
        'demo/res.partner.interest.csv',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'images':[
        'static/description/1.jpg',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'live_test_url': 'http://www.conecta.pt',
}
